spring:
  profiles:
    active: local # [local, prod]

  application:
    name: backend

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

security:
  jwt:
    base64-secret: ENC(sNYHhUvD+ubS2pa6dMF/PbvmsCyUuEwDuCS4kwtsSSlYfAfEap7x4Mzd9VEpSwtsu+lzLFnRA6bI2hhgVg0IFPkiRlBHSx1hvorTuikQIS/WUyOBy53RorcyLfxOF2r4ptlDto9J5XiCKNCRAqYXLpPJWe2YsH1ca5dWNX5Ye/c=)
    access-expiration-time: 86400000
    refresh-expiration-time: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

patientpal:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://43.201.129.48:8080

cloud:
  aws:
    s3:
      bucket: ENC(54LDKQx7340EEx/yKG/KgE3RR83t8vafcGa2ZsuQDnHQwNnTHlbhCF179X3lSzKE)
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(tEeWEIeX8ZAdndGq/K7QW6yLiyry5Vo4rpRQBKI/YNdfMOgGtpRqf/aqwR+or0DAp+PXc6Q7RE54uYAt6wBN1A==)
      secretKey: ENC(Lo/mgU4/JW5OsWM9zyKZjH8XIz1AJyYyw2N281xL7iZnHMaSJ9vu/RwXsJfuQ2vzTKU3YYeUisMVh0sSEOD0Foz774tN/ZTjd1yXto572eU=)

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/patientpal
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(uyv48BYctQJakgP+CtCpexc8sfHazuwXd+XH2ZVGeRnL1SD4f3272cV+Z21gYY7PN45UJVcluQYRVd4eVkwh0kscf5bILxCTzs5BiVp0JM6/Vq2CIuD/WJModD5P/M1hWxZaKmU0qywaaeHMLCNPH3EehJKkemVw37Zyko2IpPo=)
    username: ENC(YvhNZJW8jdIHTxSfHYpIu33tu3yWyxAoWC9wQmFINy2HZ0RK4l8pd3idd2JiMzuk)
    password: ENC(ph6RlG+iJmNuBKF9qLEgiNSlrsXteKokbapXBZOEh4e8U5B7f+Qqb6Fzq+n5MA3S)

  jpa:
    hibernate:
      ddl-auto: create

discord:
  webhook:
    url: ENC(Mm+59DLL4p0DaurvMneVpz/RrCoMA4xSXbCaCJwEA/OfMqSGaQFCFy9fW8MShdyx98eTHtwNE01VuwCEfHVqUfd+d8bLOBWEXCJdjZmUDxQaorDbDaCKj4PRnqK3gkDjpAx4SQb6qWoIZVz0P718qYpiPYNmAWNYfus4A0AP4qx/rKKWiDPqIObbXYz31rg0n92pvvEZVydUnPb8DDGNng==)
