spring:
  profiles:
    active: local # [local, prod]

  application:
    name: backend

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/patientpal
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(FB7REH9ivhDanwT9tAAGMQ+vmHedMpRjbqI/WcpFnldEh3BwDUXVfspSQi5C4oVuQtAQqCexD/K81b0CYkeJHTo7GIdFk/rjZd0X/EZ4svWjdREwBEsKJ8UGMmjsMLPJT0Qemjit7cKRvTvRfo9qis4r64G+Zuvgl+lofrSUbn8=)
    username: ENC(Ay5DwL21B0Z0dy2r5TkexrD7ncfUp5L49AF0G6Fo1qPfwOGhWORIPxly7EDHFAUW)
    password: ENC(wYREFiBZU6XZp0pvg2J9R5RhSYpn4vdmhrRuffOlV/TgkCIuZ2Zvy0yd8uM8hVz2)

  jpa:
    hibernate:
      ddl-auto: validate